FROM redis:3.2.8

FROM mysql:5.7.18

FROM mongo:3.4.3

FROM nginx

FROM elasticsearch:5.3.0

FROM ruby:2.4.1

FROM rails:5.0.1

RUN apt-get update && apt-get install -y \
imagemagick \
libmagickwand-dev \
libmagickcore-dev \
libmysqlclient-dev \
libpq-dev \
nodejs-legacy

RUN apt-get update && apt-get install -y git
