source 'https://rubygems.org'

ruby '2.3.1'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '5.1.4'
# Use mysql as the database for Active Record
gem 'mysql2', '>= 0.3.18', '< 0.5'
# Use Puma as the app server
gem 'puma', '~> 3.0'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development
group :development do
  gem 'capistrano', '~> 3.6'
  gem 'capistrano-rails', '~> 1.2'
end

#devise for user authentication
gem 'devise', '~> 4.3.0'

#bootstrap sass for styling

gem 'bootstrap-sass'

#faster jquery loading

gem 'jquery-turbolinks'

group :development, :test do
  gem 'pry'
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platform: :mri
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '~> 3.0.5'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
#gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]

# Redis gems
gem 'redis', '3.3.3'
gem 'redis-namespace', '1.5.3'
gem 'redis-rails', '5.0.1'

# for api versioning
gem 'versionist', '1.5.0'

#rorvswild
gem "rorvswild"

# view template: haml
gem 'haml', '4.0.7'

# for MongoDB
gem 'mongoid', '6.1.0'

# for facebook signup
gem 'omniauth', '~> 1.6', '>= 1.6.1'
gem 'omniauth-facebook', '~> 4.0'

# for google signup
gem 'omniauth-google-oauth2', '~> 0.4.1'

# Code coverage analysis tool
gem 'simplecov', :require => false, :group => :test

# To check quality of rails code
gem 'rails_best_practices'

# Static code analyzer for ruby
gem 'rubocop', '~> 0.48.1', require: false

# for creating background jobs, placing those jobs on multiple queues, and processing them later
gem 'resque', '~> 1.26'
gem 'resque-web', '~> 0.0.11', require: 'resque_web' # for frontend interface of viewing jobs status

# Payment gateway: Stripe
gem 'stripe', :git => 'https://github.com/stripe/stripe-ruby'

# CORS
gem 'rack-cors', '0.4.1', :require => 'rack/cors'

# Swagger
gem 'swagger-docs'

# Swagger 2.0
gem 'swagger-blocks', '2.0.0'

# For attaching roles to users
gem 'rolify', '~> 5.1'
# For authorization logic and serving assets to required roles
gem 'cancancan', '~> 2.0'

# Spree 
gem 'spree', '~> 3.3.0'
# gem 'spree_auth_devise', '~> 3.3'
gem 'spree_gateway', '~> 3.3'

# #file upload management wrapper
# gem 'paperclip', '~> 5.0.0'
#
# gem 'mongoid-paperclip', '~> 0.0.10'

#pdf converter wrapper
gem 'wicked_pdf', '~> 1.1'

gem 'wkhtmltopdf-binary'

