class SwaggerOrdersController
  include Swagger::Blocks
  swagger_path '/orders/payment.json' do
    operation :get do
      key :description, 'Build an order for user'
      parameter :header_token
      response 200 do
        key :description, 'product response'
        schema do
          key :type, :object
          property :id, type: :integer
          property :amount, type: :integer
          property :currency, type: :string
        end
      end
      response :default do
        key :description, 'unexpected error'
        schema do
          key :'$ref', :ErrorModel
        end
      end
    end
  end
  swagger_path '/orders/{id}/charge.json' do
    operation :post do
      key :description, 'Charging an order.'
      parameter :header_token
      parameter do
        key :name, :id
        key :in, :path
        key :description, 'ID of order to charge'
        key :required, true
        key :type, :integer
      end
      parameter do
        key :name, :stripeToken
        key :in, :body
        key :description, 'Token generated by stripe'
        key :required, true
        key :type, :string
      end
      response 200 do
        key :description, 'Payment successful'
        schema do
          key :type, :object
          property :success, type: :boolean
          property :message, type: :string
        end
      end
      response 422 do
        key :description, 'Error while payment'
        schema do
          key :type, :object
          property :success, type: :boolean
          property :message, type: :string
        end
      end
    end
  end
end